### ISSUE TITLE
Update index.html

### ISSUE THREAD

**Issue by Runi-VN** [MalteMagnussen/CA2#17]
Currently we have the boilerplate code. 

#### Keep:  
- [x] The link to the API documentation

#### Change:  
- [x] Remove unnecessary text
- [x] Add link to scrum.html
- [ ] Add link to any endpoints (if available)
- [x] Add links to github to showcase progress

Maybe we can take some of the setup from CA1.

**Comment by MalteMagnussen** [comment]
I will begin working on this Saturday morning, if no one has started on it before then. 

Great issue and description @Runi-VN

**Comment by MalteMagnussen** [comment]
Working on this now.

**Comment by MalteMagnussen** [comment]
" Add link to any endpoints (if available)" 

@Runi-VN Has made some very nice documentation. So I skip this part. Check out the documentation for the info.
