### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by Castau** [MalteMagnussen/CA2#24]
- [x] Remove all teacher-template files (including test files) 
- [x] Remove unused/deprecated teacher-code in resource-file. 
- [x] Remove all unused imports. 
- [x] Remove all author tags and anything else that is not being used.

**Comment by MalteMagnussen** [comment]
Great issue. Definitely has to be done before Monday.

**Comment by MalteMagnussen** [comment]
Will do this after work-out today.
