### ISSUE TITLE
[BUG] Swagger UI doesn't work properly

### ISSUE THREAD

**Issue by HrBjarup** [MalteMagnussen/CA2#26]
**Describe the bug**
An error is shown when opening the swagger UI for our API documentation. 

**To Reproduce**
1. Run project
2. Click on the API icon on our front page
3. See error

**Expected behavior**
The full documentation of our API should be shown but there seems to be something wrong with the path (even though it looks alright)

**Screenshots**
![image](https://user-images.githubusercontent.com/44898491/66266539-b257a380-e826-11e9-8ac4-c943aa45c863.png)

**Comment by Runi-VN** [comment]
Was (presumably) fixed by @HrBjarup during some of his recent DTO work.

**Comment by Runi-VN** [comment]
Actually does not work on deployment ![](https://i.imgur.com/8rDwhCY.png)

**Comment by Runi-VN** [comment]
Fixed by @MalteMagnussen. Had some issues in our EMF_creator here: #43
