### ISSUE TITLE
[BUG] GetHobbyByName is broken

### ISSUE THREAD

**Issue by Castau** [MalteMagnussen/CA2#63]
This PR #61  seems to have broken the endpoint https://maltemagnussen.com/CA2/api/search/hobby/{hobbyname}

It now returns an empty array.

**Comment by HrBjarup** [comment]
It don't understand why the endpoint doesn't work now. I used the endpoint while coding just two days ago and it worked perfectly

**Comment by Runi-VN** [comment]
It works now. Do NOT ask me why, lol
https://maltemagnussen.com/CA2/api/search/hobby/Dragonslaying
https://maltemagnussen.com/CA2/api/search/hobby/JPA

**Comment by MalteMagnussen** [comment]
Works for me atm.
