### ISSUE TITLE
[BUG] deletePerson does not properly delete all relationsships

### ISSUE THREAD

**Issue by Runi-VN** [MalteMagnussen/CA2#68]
It was reported during testing of the frontend that zip codes are not removed.

(Necessary?)

Look it through and see what is deleted and what is not.

**Comment by Runi-VN** [comment]
I just checked and after using the **delete** endpoint to delete all users, this is what is left:

Deleted:
* Address
* Person
* Person_Hobby

**Not** deleted:
* CityInfo
* Hobby
* Phone

**Comment by HrBjarup** [comment]
Imo the cities don't need to be deleted if there are no addresses attached to them.

**Comment by HrBjarup** [comment]
I am testing the **delete** endpoint atm and it deletes phones just fine now.

**Comment by HrBjarup** [comment]
After testing the endpoint some more, I've come to the conclusion that it works as intended. 
Currently it deletes:

* Address
* Person
* Person_Hobby
* Phone

and leaves:

* CityInfo
* Hobby

in the database which is fine imo.

**Comment by Runi-VN** [comment]
Great, thanks for taking a look.
