### ISSUE TITLE
Facade Class - TDD

### ISSUE THREAD

**Issue by MalteMagnussen** [MalteMagnussen/CA2#9]
To begin with, just make a personfacade.

We might need new issues for the other facades, but lets start with the person facade.

Just remember to keep it simple.

Make CRUD.

- [ ] Create
- [ ] Read
- [ ] Update
- [ ] Delete

Make sure the code is testable. Preferably you should do Test-Driven-Development and make the test before the method. 

Maybe this issue is too big? If you find its too big a mouthful, simply delete this issue, and break it down into smaller issues.

**Comment by HrBjarup** [comment]
I will work on this issue. Since we now have a person entity and a hobby entity I'll make a facade concerning those entities called SearchFacade. I won't be using TDD for the first version of the facade.
